### ISSUE TITLE
Unreliable Facebook Ads source

### ISSUE THREAD

**Issue by gphilips** [andrevandal/access-data-parser#303]
The `facebookads` source does not seem to be reliable because we check if an `fbclid` exists in the URL params, but we also find an fbclid in the URLs of simple organic posts on the facebook feed.

1. Post something with a link on Facebook
2. Click on it
3. Check the source and channel
4. See that it shouldn't be a facebook ads source

**Comment by derevandal** [comment]
Oh, thanks! Sorry about the delay.

I didn't know it.

I'm going to schedule some time to sort it out.

Thank you

**Comment by AlexandreVerhoye** [comment]
Hi ! 

We're having the same issue with `facebookads` source. On our side, it was a link posted on Instagram. 

Is it still an opened issue ? 

Thanks, have a great day !

**Comment by andrevandal** [comment]
@AlexandreVerhoye @gphilips hey guy, I've removed the part that determinate this behavior and just release the `v1.5.1`.
